### ISSUE TITLE
Change Node js queries

### ISSUE THREAD

**Issue by aqibali27** [sagarankoliya/realtime-private-chat-nodejs-socketio-vuejs-laravel#10]
Hi, i need some help.
i want to change the node js queries in helper,js file to ajax request and call the laravel routes. How can i do that?

**Comment by sagarankoliya** [comment]
Hi @aqibali27,

For ajax call in nodejs you can use any http client library like request, axios, and laravel side you can make api route.

Let me know if anything unclear

Thanks,
Sagar
