### ISSUE TITLE
want to connect this with objective c 

### ISSUE THREAD

**Issue by ebrahimElgeded** [sagarankoliya/realtime-private-chat-nodejs-socketio-vuejs-laravel#11]
want to connect this with objective c get connect with socket - get the chat list but not apple to get messages from other users .

**Comment by ebrahimElgeded** [comment]
[socket on:@"getMessagesResponse" callback:^(NSArray* data, SocketAckEmitter* ack) {
            NSLog(@"getMessagesResponse");
        }];

        [socket on:@"addMessages" callback:^(NSArray* data, SocketAckEmitter* ack) {
            NSLog(@"addMessages");
        }];
        [socket on:@"addMessagesResponse" callback:^(NSArray* data, SocketAckEmitter* ack) {
            NSLog(@"addMessagesResponse");
        }];
    
    
    
        [[socket emitWithAck:@"addMessagesResponse" with:@[@"2",@"3"]] timingOutAfter:0 callback:^(NSArray* data) {
            NSLog(@"addMessagesResponse ack",data);
            //  printf(data);
            //      //  [socket emit:@"update" with:@[@{@"amount": @(cur + 2.50)}]];
        }];
    
        [socket onAny:^(SocketAnyEvent *event) {
            NSLog(@"Receive Event %@", event);
        //  [self updateME];

//            NSDictionary *packet = @{ @"fromUserId": @"2",@"toUserId" : @"1"};
//           [socket emit:@"getMessages" with:@[packet]];
            
        }];

**Comment by ebrahimElgeded** [comment]
[        [socket on:@"getMessagesResponse" callback:^(NSArray* data, SocketAckEmitter* ack) {
            NSLog(@"getMessagesResponse");
        }];

        [socket on:@"addMessages" callback:^(NSArray* data, SocketAckEmitter* ack) {
            NSLog(@"addMessages");
        }];
        [socket on:@"addMessagesResponse" callback:^(NSArray* data, SocketAckEmitter* ack) {
            NSLog(@"addMessagesResponse");
        }];
    
    
    
        [[socket emitWithAck:@"addMessagesResponse" with:@[@"2",@"3"]] timingOutAfter:0 callback:^(NSArray* data) {
            NSLog(@"addMessagesResponse ack",data);
            //  printf(data);
            //      //  [socket emit:@"update" with:@[@{@"amount": @(cur + 2.50)}]];
        }];
    
        [socket onAny:^(SocketAnyEvent *event) {
            NSLog(@"Receive Event %@", event);
        //  [self updateME];

//            NSDictionary *packet = @{ @"fromUserId": @"2",@"toUserId" : @"1"};
//           [socket emit:@"getMessages" with:@[packet]];
            
        }];](url)

**Comment by sagarankoliya** [comment]
Hi,

Please send me what was the error you are getting, and also please check chat server is properly configured or not. any error in node server?

Thanks,

**Comment by ebrahimElgeded** [comment]
No NO problem on server only we need to know how to connect two user in chat box from mobile ios system

**Comment by ebrahimElgeded** [comment]
؟

**Comment by sagarankoliya** [comment]
Hii, 

You have to create same chat clients as i have created in vue js in same project you need to use same socket events as use in vue js file you need to find it.

Let me know if anything unclear

Thanks,
