### ISSUE TITLE
Disable export NODE_ENV=dev 

### ISSUE THREAD

**Issue by erfanhemmati** [sagarankoliya/realtime-private-chat-nodejs-socketio-vuejs-laravel#12]
How i disable export NODE_ENV=dev ?

**Comment by sagarankoliya** [comment]
Hi

Didn't get your point, can you please elaborate.

Thanks,

**Comment by erfanhemmati** [comment]
my question is. What does the following piece of code do?
export NODE_ENV=dev

**Comment by sagarankoliya** [comment]
It will set program environment, like for development or production

**Comment by erfanhemmati** [comment]
How i can disable this command ?

**Comment by sagarankoliya** [comment]
Hii,  

Why you are need to disable this? this is the best way to use environment in node. 

anyway If you need to remove this command, find this string in node project 'process.env.XXX' XXX is like PORT, HOST,  etc and replace with your config directly.

Thanks,
