### ISSUE TITLE
Error: listen EADDRNOTAVAIL: address not available 3.13.202.232:3000

### ISSUE THREAD

**Issue by jaswinder2412** [sagarankoliya/realtime-private-chat-nodejs-socketio-vuejs-laravel#13]
I am uploading it on my server and this is giving me an error below

https://prnt.sc/pji55n

**Comment by sagarankoliya** [comment]
Hii

Can you please set this ip 0.0.0.0 in node environment and try again.

Let me know if still facing issue

Thanks,
