### ISSUE TITLE
i got error after apply command npm run start

### ISSUE THREAD

**Issue by Meera9** [sagarankoliya/realtime-private-chat-nodejs-socketio-vuejs-laravel#14]
Error: Cannot find module 'nice-try'
    at Function.Module._resolveFilename (module.js:547:15)

**Comment by sagarankoliya** [comment]
Which node version are you using?

**Comment by sagarankoliya** [comment]
Hi @Meera9,

i am closing this issue, Let me know if you are still facing any issue

Thanks,
