### ISSUE TITLE
Nodejs Cpanel Hosting

### ISSUE THREAD

**Issue by DhaduBum** [sagarankoliya/realtime-private-chat-nodejs-socketio-vuejs-laravel#15]
Hi,
First of all, a great project. 
I was easily able to implement it locally in my project. I have bought a2zhosting of nodejs.  When I try to implement it online it has error of time out.

**Comment by sagarankoliya** [comment]
Hii, 

Can you please share the error screenshot, so i can better explain about that.

Thanks,

**Comment by DhaduBum** [comment]
The error says
failed: Error during WebSocket handshake: 'Connection' header is missing

**Comment by DhaduBum** [comment]
Can I have your email address so that we can have a screen sharing session ?

**Comment by sagarankoliya** [comment]
Please check your cpanel node js version? It is match with project requirement, for project requirement you can read md file, and also which port you are using for node server,  please check used port is open or not.

If any issues share screenshot of errors
