### ISSUE TITLE
How Can I add Emoji to this demo?

### ISSUE THREAD

**Issue by bharatkaneriya** [sagarankoliya/realtime-private-chat-nodejs-socketio-vuejs-laravel#16]
I want to add Emoji in chat module can you please help me for the same.

**Comment by sagarankoliya** [comment]
How can i help you?

**Comment by bharatkaneriya** [comment]
I want to add Emoji in this demo so can you please suggest me any best package for this demo.

**Comment by miladmodaresi** [comment]
> I want to add Emoji in this demo so can you please suggest me any best package for this demo.

I think you need this package
https://www.npmjs.com/package/rm-emoji-picker
