### ISSUE TITLE
Please provide a video or vlog reference so i can implement this.

### ISSUE THREAD

**Issue by Vikrant659** [sagarankoliya/realtime-private-chat-nodejs-socketio-vuejs-laravel#17]
Hi,
Can you please make a vlog or video that how did you implemented this. Since i do have some custom requirements and this would really help me to get the flow of this chat application.
Thanks

**Comment by sagarankoliya** [comment]
Hi,

Right now I am busy with something, I will provide the video soon, in the meanwhile please try to understand the project flow and also see the readme.md file.

Thank you,

**Comment by Vikrant659** [comment]
Thanks for getting back in such a short time.
But there are so many js files that i'm not getting some of the things and in the readme.md file there are steps to install and run the project which is working fine.
However, when you make a video or vlog about it then please let me know.
Otherwise, You can also elaborate some information in readme.md file that will help alot too.

**Comment by sagarankoliya** [comment]
Hi, 

You can review below these files

Server side : node js folder all files

Client side : resources/assets/js/chat.js

Thanks,

**Comment by Vikrant659** [comment]
Ok thanks, I think this will help.

**Comment by Vikrant659** [comment]
Hi @sagarankoliya,
Hope you are doing well.
I just have a query that if i'm using this code on live server and there isn't any port no for live DB. Then how can i connect the app with live server DB.

**Comment by sagarankoliya** [comment]
Hii

Sorry Didn't get you, did you mean mysql port?

mysql have default port 3306

Thanks
