### ISSUE TITLE
Please remove "{{ env('WS_URL') }}" from layout file.

### ISSUE THREAD

**Issue by Vikrant659** [sagarankoliya/realtime-private-chat-nodejs-socketio-vuejs-laravel#20]
I was struggling to get this code working.
And after struggling with this code for half day. I saw that the:-

`<meta name="ws_url" content="{{ env('WS_URL') }}">`

The content of above meta tag was coming empty. This is because you can't access env variables directly. Now you have to first declare variables in config file and then you have to access them from config file. 
So, please update code. I don't want anyone to get this kind of silly problem 😂 .
Otherwise the code is working perfectly fine.

**Comment by sagarankoliya** [comment]
These are not silly mistakes, you did not follow the steps given in the readme.md file properly, you need to add WS_URL to your .env file.

  Follow the steps correctly then try again 😂

**Comment by Vikrant659** [comment]
I added
![image](https://user-images.githubusercontent.com/29250004/108727244-5e01b080-754e-11eb-9163-007c9ed6cfc4.png)
Above image is from IDE

![image](https://user-images.githubusercontent.com/29250004/108727469-a02af200-754e-11eb-922e-5370d490aa8b.png)
Above image is of source code in browser

But you can't get env variables like this.
You can check your self
Believe me 😂.

**Comment by sagarankoliya** [comment]
For mine env var use  like this is working fine and tested also, but not sure about your side why this not working, did you use config:cache?

**Comment by sagarankoliya** [comment]
> I added
> ![image](https://user-images.githubusercontent.com/29250004/108727244-5e01b080-754e-11eb-9163-007c9ed6cfc4.png)
> Above image is from IDE
> 
> ![image](https://user-images.githubusercontent.com/29250004/108727469-a02af200-754e-11eb-922e-5370d490aa8b.png)
> Above image is of source code in browser
> 
> But you can't get env variables like this.
> You can check your self
> Believe me 😂.
Also need to add in .env file

**Comment by Vikrant659** [comment]
> For mine env var use like this is working fine and tested also, but not sure about your side why this not working, did you use config:cache?

Yes

**Comment by sagarankoliya** [comment]
**env(...) function will not work after you cached the config.**

https://stackoverflow.com/questions/43243732/laravel-5-env-always-returns-null
