### ISSUE TITLE
Why socket if access could not connect, this project still local computer not hosting

### ISSUE THREAD

**Issue by anisfajar** [sagarankoliya/realtime-private-chat-nodejs-socketio-vuejs-laravel#23]
this still try in my local computer, i want test access from other computer  .. I run in my local computer this  **php artisan serve --host=192.168.20.xxx** ..

when I access it on another computer a notification appears on the socket **Could not connect to server**

**Comment by sagarankoliya** [comment]
Hi @anisfajar,

You need to set below laravel env

WS_URL=http://192.168.20.xx:3000/

And also start node server on http://192.168.20.xx:3000 instead on http:// localhost:3000

Thanks,

**Comment by anisfajar** [comment]
oke solved , thanks @sagarankoliya
