### ISSUE TITLE
Run the App on Server and Configuration

### ISSUE THREAD

**Issue by mohsen4p** [sagarankoliya/realtime-private-chat-nodejs-socketio-vuejs-laravel#24]
Thank you for great chat application, I ran it On local host by laragon.
But i tried to ran on VPS server and couldn't. please give us a step by step to use this great application.

**Comment by sagarankoliya** [comment]
Hi, 

All steps are given in readme.md file,  and also what type of issue are you facing on VPS

**Comment by mohsen4p** [comment]
hi
all the step running great at local system by laragon
but when I run it on VPS the chat services didn't sync and say connection error, i think client side try to connect with vps 80 port not 3000 that socket listening. please help me I implement on vps in step by step

**Comment by sagarankoliya** [comment]
Hi, 

You need to set below laravel env

WS_URL=http://YOUR IP HERE:3000/

And also start node server on http://YOUR IP HERE:3000 instead on http:// localhost:3000

On vps 3000 port must open, and node server must running on ip instead of localhost

Thanks,

**Comment by mohsen4p** [comment]
thanks,
you are great...
