### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by balap777** [sagarankoliya/realtime-private-chat-nodejs-socketio-vuejs-laravel#3]
Hi thanks for your code which i needed for longtime but i need your help.How can i use this code in my existing project as i cannot directly do composer install it will erase all the code of my project can to tell me the specific files which to include for chat to get started and how to show only the specific user in online section.
Thanks in advance and once again thank you for your code

**Comment by sagarankoliya** [comment]
1. copy nodejs and js directory from public and paste it into your project public location.
2. copy or adjust home.blade.php file from resources/views acording to your project layout.
3. To dispay specific user as per your requirement chage the query in /public/nodejs/utils/helper.js getChatList() function.
4. Also add below line in your .env WS_URL=http://localhost:3000/
5. Also add below line in your layout file
```
<meta name="ws_url" content="{{ env('WS_URL') }}">
<meta name="user_id" content="{{ Auth::id() }}">

```
6. Also follow migration files
7. after that follow the Step : 5,6,7

**Comment by balap777** [comment]
Hello sagar tried your given steps on laravel 5.6 but i am getting this error


![image](https://user-images.githubusercontent.com/42376010/45611989-12927080-ba7f-11e8-80b8-dcafc835136e.png)


and if i change app.js of my project with your app.js file then only vue tags are shown

![image](https://user-images.githubusercontent.com/42376010/45612059-57b6a280-ba7f-11e8-991c-57b66a85a526.png)

am i doing some thing wrong

**Comment by sagarankoliya** [comment]
I think you not start node server, and please read all step carefully.

**Comment by balap777** [comment]
the node server was running still got the error i am using laravel 5.6

**Comment by sagarankoliya** [comment]
ok what type of error you getting. you include all js in your layout file?

**Comment by balap777** [comment]
i have attached the screen shot above

**Comment by sagarankoliya** [comment]
i think you not add chat.js file in your layout.

**Comment by balap777** [comment]
added still not working can you test this on laravel 5.6 by your end  it would be a great help did every step as you told but still not working i think the issue is with bootstrap or any other package or may be with laravel version

**Comment by sagarankoliya** [comment]
i think not a version problem, please send me a screenshot of your laravel layout file and chat code file

**Comment by balap777** [comment]
used the same file of your project did not edit any thing from my end same as yours

**Comment by sagarankoliya** [comment]
ok but send me screenshot your layout because you copy my code to laravel 5.6 so i think you not proper configure code
