### ISSUE TITLE
No configurations found in configuration

### ISSUE THREAD

**Issue by mostafa6765** [sagarankoliya/realtime-private-chat-nodejs-socketio-vuejs-laravel#4]
I have configure 

```js
{
    "dbConfig": {
        "host": "localhost",
        "port": 3306,
        "user": "root",
		"password": "mysql",
		"database": "chat"
    }
}
``` 
but show errors 
```bash 
[nodemon] starting `node ./index.js`
WARNING: No configurations found in configuration directory:C:\Users\Mostafa Kamal\realtime-private-chat-nodejs-socketio-vuejs-laravel\public\nodejs\config
WARNING: To disable this warning set SUPPRESS_NO_CONFIG_WARNING in the environment.
C:\Users\Mostafa Kamal\realtime-private-chat-nodejs-socketio-vuejs-laravel\public\nodejs\node_modules\config\lib\config.js:203
    throw new Error('Configuration property "' + property + '" is not defined');
    ^

Error: Configuration property "dbConfig.host" is not defined
    at Config.get (C:\Users\Mostafa Kamal\realtime-private-chat-nodejs-socketio-vuejs-laravel\public\nodejs\node_modules\config\lib\config.js:203:11)
    at new Db (C:\Users\Mostafa Kamal\realtime-private-chat-nodejs-socketio-vuejs-laravel\public\nodejs\utils\db.js:10:17)
    at Object.<anonymous> (C:\Users\Mostafa Kamal\realtime-private-chat-nodejs-socketio-vuejs-laravel\public\nodejs\utils\db.js:36:18)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by sagarankoliya** [comment]
You have to run this command

Go to project directory using Terminal / CMD Open public/nodejs folder

1. export NODE_ENV=dev
2. npm start

**Comment by mostafa6765** [comment]
Thanks mate . solved ❤️

**Comment by nexuslink-sumit** [comment]
still I got error on windows 10.
![image](https://user-images.githubusercontent.com/48318750/55885106-f2670200-5bc6-11e9-942d-1b33fabc1304.png)

**Comment by nexuslink-sumit** [comment]
I still got error on windows 10.
Image for configuration file for laravel and node.
I tried with ("host": "localhost", OR "host": "127.0.0.1") both doesn't work.
![image](https://user-images.githubusercontent.com/48318750/55885375-7620ee80-5bc7-11e9-9b78-888f52fcfb95.png)

Image shows error on execution.
![image](https://user-images.githubusercontent.com/48318750/55885392-7caf6600-5bc7-11e9-9728-076e1198336c.png)

**Comment by sagarankoliya** [comment]
Hi @nexuslink-sumit,

I think node  environment not properly configured, please follow step carefully.

Still any issues let me know

Thanks

**Comment by codeajeeb** [comment]
> I have configure
> 
> ```js
> {
>     "dbConfig": {
>         "host": "localhost",
>         "port": 3306,
>         "user": "root",
> 		"password": "mysql",
> 		"database": "chat"
>     }
> }
> ```
> 
> but show errors
> 
> ```shell
> [nodemon] starting `node ./index.js`
> WARNING: No configurations found in configuration directory:C:\Users\Mostafa Kamal\realtime-private-chat-nodejs-socketio-vuejs-laravel\public\nodejs\config
> WARNING: To disable this warning set SUPPRESS_NO_CONFIG_WARNING in the environment.
> C:\Users\Mostafa Kamal\realtime-private-chat-nodejs-socketio-vuejs-laravel\public\nodejs\node_modules\config\lib\config.js:203
>     throw new Error('Configuration property "' + property + '" is not defined');
>     ^
> 
> Error: Configuration property "dbConfig.host" is not defined
>     at Config.get (C:\Users\Mostafa Kamal\realtime-private-chat-nodejs-socketio-vuejs-laravel\public\nodejs\node_modules\config\lib\config.js:203:11)
>     at new Db (C:\Users\Mostafa Kamal\realtime-private-chat-nodejs-socketio-vuejs-laravel\public\nodejs\utils\db.js:10:17)
>     at Object.<anonymous> (C:\Users\Mostafa Kamal\realtime-private-chat-nodejs-socketio-vuejs-laravel\public\nodejs\utils\db.js:36:18)
>     at Module._compile (module.js:652:30)
>     at Object.Module._extensions..js (module.js:663:10)
>     at Module.load (module.js:565:32)
>     at tryModuleLoad (module.js:505:12)
>     at Function.Module._load (module.js:497:3)
>     at Module.require (module.js:596:17)
>     at require (internal/module.js:11:18)
> [nodemon] app crashed - waiting for file changes before starting...
> ```

same issue occurs with me help me out
