### ISSUE TITLE
Uncaught Error: Cannot find module "vue-socket.io"

### ISSUE THREAD

**Issue by Pooja153Sawant** [sagarankoliya/realtime-private-chat-nodejs-socketio-vuejs-laravel#5]
Hi,
    I tried your code. After integrating it in my project I am facing " Uncaught Error: Cannot find module "vue-socket.io"" such error. I had also attached screenshot for that issue. 
    

![screenshot](https://user-images.githubusercontent.com/43174564/45585544-bc4cf280-b903-11e8-82fe-bc960d4fdbb9.png)

**Comment by sagarankoliya** [comment]
We have not you vue-socket.io  library in this project, so please clone this project again and follow given step properly.
