### ISSUE TITLE
How to make this app ready for production?

### ISSUE THREAD

**Issue by SankhaRx** [sagarankoliya/realtime-private-chat-nodejs-socketio-vuejs-laravel#6]
I want to deploy this app in Godaddy hosting with Apache and PHP, how can I do this?

**Comment by sagarankoliya** [comment]
If your Godaddy hosting support to install nodejs then you can do it.

**Comment by SankhaRx** [comment]
Yes I have installed Node.js with putty, now I want to know how can I handle these commands in server
**export NODE_ENV=dev
npm start**
and
**php artisan serve**
how can I automate these command?

**Comment by sagarankoliya** [comment]
1. For nodejs use http://pm2.keymetrics.io/
2. For PHP if you have domain , 

- so point your domain to public/index.php in laravel
- if you have no domain then
- move index.php from public directory to project root  directory then
- changed below two lines 

require __DIR__.'/bootstrap/autoload.php';
$app = require_once __DIR__.'/bootstrap/app.php';

**Comment by SankhaRx** [comment]
Ok thanks I will try and let you know. Thanks for this great app. I am closing the issue for now..

**Comment by W3bDeveloper7** [comment]
pm2 start index.js or what ?

**Comment by sagarankoliya** [comment]
Hii

Yes index.js

**Comment by W3bDeveloper7** [comment]
Thanks, it working but i have another problem now .. i can send from one side and receive at the other side but can't reply or send from also  can't see if any one is online or not

**Comment by sagarankoliya** [comment]
Hii, 

May be node server not properly configured or if any error please send me screenshot.

Also please read readme.md file all dependency are installed

Thanks
