### ISSUE TITLE
file sharing not working

### ISSUE THREAD

**Issue by jithinlal** [sagarankoliya/realtime-private-chat-nodejs-socketio-vuejs-laravel#7]
Hai, great work by the way.

But the file sharing feature is not working?

**Comment by sagarankoliya** [comment]
Which kind of error you are facing with file sharing?

**Comment by jithinlal** [comment]
Not errors, but the file on chat is simply loading. It is not getting send. And not stored in the database as well

**Comment by sagarankoliya** [comment]
It was a little bug , i have already fixed it , please pull changes.

**Comment by jithinlal** [comment]
Ok.

There is one more error, when i am doing npm start.

The error message is posted here

> Error: Configuration property "dbConfig.host" is not defined

**Comment by sagarankoliya** [comment]
Please follow the step properly. it work fine.

```
Step : 7

Start Node JS Chat Server

Go to project directory using Terminal / CMD Open public/nodejs folder

export NODE_ENV=dev
npm start


```

**Comment by jithinlal** [comment]
It's working perfectly.

This is great work.

Thank you brother
